name: default-project

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  add_to_project:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: bchess/default-project-board-action@project_id
      with:
        github_token: "v1.7d77273c343c1221d27846afbafd66264c6333fe"
        repository: ${{ github.repository }}
        issue: ${{ github.event.issue.number }}
        project: MDc6UHJvamVjdDQ4MDE4ODc=

