name: default-project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
    - uses: bchess/default-project-board-action@project_id
      with:
        private_key: ${{ secrets.SUPERCOMPUTING_ISSUEBOT_PRIVATE_KEY }}
        app_id: 70438
        project: "Supercomputing Team"
        repository: ${{ github.repository }}
        issue: ${{ github.event.issue.number }}
        pull_request: ${{ github.event.pull_request.number }}

